collections:
  authors:
    output: true

url: "hexdrinkers.com" #base for site
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2

# paginate: 15
# paginate_path: "/articles/:num/"
pagination:
  enabled: true
  per_page: 15
  title: ":title"
  sort_reverse: true
  trail:
    before: 2
    after: 2
  # permalink: "/articles/:num/"
excerpt_separator: <!--more-->

# Google SEO stuff
title: "The Hexdrinkers"
description: "Magic the Gathering and Magic Arena decks, strategy, and commentary"
twitter:
  username: hexdrinkers
  card: summary
social:
  name: "The Hexdrinkers"
  links:
    - https://twitter.com/hexdrinkers

logo: /assets/images/logo.png

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      showSeries: true
  - scope:
      path: ""
    values:
      layout: "default"
