collections:
  authors:
    output: true

url: "https://brewcrew.net" #base for site
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 15
excerpt_separator: <!--more-->

# Google SEO stuff
title: "The Brew Crew"
description: "Magic the Gathering and Magic Arena decks, strategy, and commentary"
twitter:
  username: TheBrewCrew13
  card: summary
social:
  name: "The Brew Crew"
  links:
    - https://twitter.com/TheBrewCrew13

logo: /assets/images/logo.png

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      showSeries: true
  - scope:
      path: ""
    values:
      layout: "default"
